// <auto-generated />
using System;
using KonyvtarAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KonyvtarAPI.Migrations
{
    [DbContext(typeof(KonyvtarDBContext))]
    [Migration("20250516174147_new1")]
    partial class new1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("KonyvtarAPI.Kolcsonzes", b =>
                {
                    b.Property<int>("KolcsonzesSzam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("KolcsonzesIdeje")
                        .HasColumnType("TEXT");

                    b.Property<int>("LeltariSzam")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OlvasoSzam")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("VisszahozasHatarido")
                        .HasColumnType("TEXT");

                    b.HasKey("KolcsonzesSzam");

                    b.ToTable("Kolcsonzesek");
                });

            modelBuilder.Entity("KonyvtarAPI.Konyvek", b =>
                {
                    b.Property<int>("LeltariSzam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("KiadasEve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kiado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Szerzo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("LeltariSzam");

                    b.ToTable("Konyvek");
                });

            modelBuilder.Entity("KonyvtarAPI.Olvasok", b =>
                {
                    b.Property<int>("OlvasoSzam")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("OlvasoNev")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("SzuletesiDatum")
                        .HasColumnType("TEXT");

                    b.HasKey("OlvasoSzam");

                    b.ToTable("Olvasok");
                });
#pragma warning restore 612, 618
        }
    }
}
